        formatGeneralDictionary,
        lookupGeneralDictionary,
        prepareIdentifier,
        programmingPhraseParts,
        splitIdentifier,
        tokenizeChinese,
        toCamelCase,
        toKebabCase,
        toPascalCase,
        toScreamingSnakeCase,
        toSnakeCase,
        translate
    };
}
